# Generated by Django 4.2.3 on 2023-10-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_usuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/default.png', null=True, upload_to='fotos'),
        ),
    ]
