# Generated by Django 4.2.3 on 2023-10-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_alter_usuarios_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='userName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
